version: 0.2
# Based on the Docker documentation, must include the DOCKER_CLI_EXPERIMENTAL environment variable
# https://docs.docker.com/engine/reference/commandline/manifest/

phases:
    pre_build:
        commands:
            - echo Logging in to Docker Hub...
            - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker manifest...
            - export DOCKER_CLI_EXPERIMENTAL=enabled
            - docker manifest create $IMAGE_REPO_NAME:$TAG --amend $IMAGE_REPO_NAME:$TAG-aarch64 --amend $IMAGE_REPO_NAME:$TAG-x86_64

    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker manifest push $IMAGE_REPO_NAME:$TAG
            - docker manifest inspect $IMAGE_REPO_NAME
